### ISSUE TITLE
Regional statistician admin tools

### ISSUE THREAD

**Issue by crast** [tmlpstats/tmlpstats#16]
- managing a region #27 
- creating new users #28

**Comment by pdarg** [comment]
Wish list:
- Invite new users to a center
- Manage "managed" user accounts (change passwords, etc)
- Update/add quarter dates for current and future quarters
- Add/Update center/regional settings
- Mark a stats report accepted (we won't accept any new submissions for that week from local statisticians, unless unlocked)
- Mark a global report as final (no more updates to any stats reports for that region unless unlocked)
- Reimport an existing report (without having to download it)
- Provide overrides on special case processing (allow repromises after/before classroom 2, allow processing even if there's a red error, etc)

**Comment by pdarg** [comment]
Requests from EME: 
1. - verify the class dates in region (as you mentioned)
2. - to set the mailing list (apart from the one provided by local statisticians in their report)
3. - to have extra rows for statisticians (Some centers have multiple statisticians)
4. - to have access to reset the passwords for teams
